# Generated by Django 6.0 on 2025-12-31 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='candidatedp/')),
                ('resume', models.FileField(null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate_app.candidate')),
            ],
        ),
    ]
