# Generated by Django 6.0 on 2025-12-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_image', models.ImageField(null=True, upload_to='companyimage/')),
                ('job_role', models.CharField(max_length=200)),
                ('skills_required', models.TextField()),
                ('job_description', models.TextField()),
                ('salary_range', models.CharField(max_length=200)),
                ('experinece_required', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('vacancy', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=100)),
                ('industry_type', models.CharField(max_length=200)),
                ('job_posted_on', models.DateField(auto_now_add=True)),
                ('last_date_to_apply', models.DateField()),
                ('hiring_process', models.TextField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_app.candidate')),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.jobdetail')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='recruiterdp/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter')),
            ],
        ),
    ]
